### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lolminerxmrig** [HamzaEzzRa/MLPDR#3]
main.py
Traceback (most recent call last):
  File "C:\Users\A\Downloads\Compressed\MLPDR-main\MLPDR-main\main.py", line 9, in <module>
    window.setup(1280, 720)
  File "C:\Users\A\Downloads\Compressed\MLPDR-main\MLPDR-main\gui.py", line 174, in setup
    self.detector.load_model("./weights/detection/yolov3-detection_final.weights", "./weights/detection/yolov3-detection.cfg")
  File "C:\Users\A\Downloads\Compressed\MLPDR-main\MLPDR-main\detection.py", line 8, in load_model
    self.net = cv2.dnn.readNet(weight_path, cfg_path)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\dnn\src\darknet\darknet_importer.cpp:210: error: (-212:Parsing error) Failed to open NetParameter file: ./weights/detection/yolov3-detection.cfg in function 'cv::dnn::dnn4_v20221220::readNetFromDarknet'

**Comment by lolminerxmrig** [comment]
not support Arabic numbers
